[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.pdo",
  "php82Extensions.pgsql",
  "php82Extensions.tokenizer",
  "php82Packages.composer",
  "curl",
  "nodejs_20" # ✅ tambahkan ini
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install", # atau "npm ci" kalau pakai package-lock.json
  "npm run build"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
