[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.pdo",
  "php82Extensions.pgsql",
  "php82Extensions.tokenizer",
  "php82Packages.composer",
  "curl",
  "nodejs_20"
]
cmds = [
  "cp .env.production .env",                               # pastikan .env aktif
  "touch database/database.sqlite",                         # buat database kosong kalau belum ada
  "mkdir -p storage/logs && touch storage/logs/laravel.log" # supaya Laravel bisa tulis log
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "chmod -R 775 storage bootstrap/cache",
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan config:cache",
  "php artisan route:cache",
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "php -S 0.0.0.0:$PORT -t public"
