[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.pdo",
  "php82Extensions.pgsql",
  "php82Extensions.tokenizer",
  "php82Packages.composer",
  "curl",
  "nodejs_20"
]
cmds = [
  "cp .env.production .env",
  "mkdir -p bootstrap/cache storage/logs",
  "chmod -R 775 bootstrap/cache storage"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
