[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.pdo",
  "php82Extensions.pgsql",
  "php82Extensions.tokenizer",
  "php82Packages.composer",
  "curl",
  "nodejs_20"
]
cmds = [
  "cp .env.production .env"  # Pastikan file .env ada sebelum artisan dipanggil
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "chmod -R 775 storage bootstrap/cache",             # Wajib untuk Laravel bisa menulis log & cache
  "php artisan config:clear",                          # Bersihkan cache lama
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan config:cache",                          # Re-cache config setelah .env tersedia
  "php artisan route:cache",
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "php -S 0.0.0.0:$PORT -t public"
