[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
SESSION_DRIVER = "database"
CACHE_DRIVER = "database"
QUEUE_CONNECTION = "database"
